language: csharp
solution: src/OpenLinq.sln
install:
  - nuget restore src/OpenLinq.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release src/OpenLinq.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./src/OpenLinq.Tests/bin/Release/OpenLinq.Tests.dll